### ISSUE TITLE
Emoji Always added in last of text

### ISSUE THREAD

**Issue by vjayrajput** [ankushsachdeva/emojicon#19]
HI I am write "android" in edittext and  add smiley then it add in last of "android+smiley_icon" now i move cursor to between "android" like "an" and "droid" then after i add smiley and its alwasy add in last of text in edittext like "android+smiley_icon" but in practical it add between "an+smiley_icon+droid" .
 So how to fix this issue?

Thanks for good library

**Comment by saket** [comment]
A simple Google search would have returned you the solution. Here, use this method:

```
private void insertAtCurrenCursorPosition(CharSequence whatToInsert){
    if(mReplyField.getText() == null){
        mReplyField.append(whatToInsert);
        return;
    }
    mReplyField.getText().insert(mReplyField.getSelectionStart(), whatToInsert);
}
```

**Comment by vjayrajput** [comment]
@ankushsachdeva  hi please update this code in your example MainActivity.java class

popup.setOnEmojiconClickedListener(new OnEmojiconClickedListener() {

```
        @Override
        public void onEmojiconClicked(Emojicon emojicon) {
            if (emojiconEditText == null || emojicon == null) {
                return;
            }

            int start = emojiconEditText.getSelectionStart();
            int end = emojiconEditText.getSelectionEnd();
            if (start < 0) {
                emojiconEditText.append(emojicon.getEmoji());
            } else {
                emojiconEditText.getText().replace(Math.min(start, end),
                        Math.max(start, end), emojicon.getEmoji(), 0,
                        emojicon.getEmoji().length());
            }
        }
    });
```

This is resolved issue of always display emoji end of text.

**Comment by ankushsachdeva** [comment]
Thanks @vjayrajput and @Saketme 
7284b7d42370b33c64b3809dd5e2e2833f445af8
