### ISSUE TITLE
Gradle Support for Android Studio

### ISSUE THREAD

**Issue by iAviatorJose** [ankushsachdeva/emojicon#2]
Is there any gradle support for this project:
I mean to say any compile statement to integrate this project with an application.

For Integrating your project in my Android Studio Project i used the jar file generated in the bin 
folder of your library, the library gets integrated and the app runs but where i have used the 
EmojiconEditText and EmojiconTextView we get the following error.

01-07 10:27:45.161: E/AndroidRuntime(27777): android.view.InflateException: Binary XML file line #47: Error inflating class com.mypurpleslate.purpleslate.EditTextBackEvent
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at com.mypurpleslate.purpleslate.ChatDetailsFragment.onCreateView(ChatDetailsFragment.java:223)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.os.Handler.handleCallback(Handler.java:733)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.os.Looper.loop(Looper.java:157)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.app.ActivityThread.main(ActivityThread.java:5633)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at java.lang.reflect.Method.invokeNative(Native Method)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at java.lang.reflect.Method.invoke(Method.java:515)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at dalvik.system.NativeStart.main(Native Method)
01-07 10:27:45.161: E/AndroidRuntime(27777): Caused by: java.lang.reflect.InvocationTargetException
01-07 10:27:45.161: E/AndroidRuntime(27777):    at java.lang.reflect.Constructor.constructNative(Native Method)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
01-07 10:27:45.161: E/AndroidRuntime(27777):    ... 21 more
01-07 10:27:45.161: E/AndroidRuntime(27777): Caused by: java.lang.NoClassDefFoundError: github.ankushsachdeva.emojicon.R$drawable
01-07 10:27:45.161: E/AndroidRuntime(27777):    at github.ankushsachdeva.emojicon.EmojiconHandler.<clinit>(EmojiconHandler.java:36)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at github.ankushsachdeva.emojicon.EmojiconEditText.onTextChanged(EmojiconEditText.java:57)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.TextView.setText(TextView.java:4015)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.TextView.setText(TextView.java:3869)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.EditText.setText(EditText.java:85)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.TextView.<init>(TextView.java:1372)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.EditText.<init>(EditText.java:60)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at android.widget.EditText.<init>(EditText.java:56)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at github.ankushsachdeva.emojicon.EmojiconEditText.<init>(EmojiconEditText.java:39)
01-07 10:27:45.161: E/AndroidRuntime(27777):    at com.mypurpleslate.purpleslate.EditTextBackEvent.<init>(EditTextBackEvent.java:22)
01-07 10:27:45.161: E/AndroidRuntime(27777):    ... 24 more
01-07 10:27:45.171: E/ActivityManager(934): App crashed! Process: com.mypurpleslate.purpleslate

**Comment by ankushsachdeva** [comment]
Its an eclipse project, so you'll have to export it as a gradle project using eclipse first.
Also, this project contains resources so importing a compiled jar file will not work.

**Comment by IHNEL** [comment]
#61
