### ISSUE TITLE
Toggle not working on android API >=21 

### ISSUE THREAD

**Issue by Jaymo** [ankushsachdeva/emojicon#30]
Works as expected on lower api levels but from API level 21 the toggle fails. The popup shows on top of the edittext fields and the toggle button is obscured. Secondly there are intermittent times when the gridview of emojis disappears and leaves behind the header

**Comment by Jaymo** [comment]
Solved it using this hack https://github.com/takenet/emojicon/blob/master/emojicon/src/main/java/github/ankushsachdeva/emojicon/EmojiconsPopup.java

**Comment by rajazeeshanahmed** [comment]
Thanks buddy. It helps me to solve this problem.
