### ISSUE TITLE
The grid item click not working for versions below lollipop

### ISSUE THREAD

**Issue by ashishsakarkar2020** [ankushsachdeva/emojicon#5]
Hi Ankush,

Thanks for the great project.

The emoji grid item click is not working on 2.3 and and 4.2.2 devices. However with lollipop the clicks work fine...can you suggest?

Thanks,
Ashish

**Comment by ankushsachdeva** [comment]
I tested the library on Samsung galaxy mini (Version 2.3.6). I am not able to reproduce your bug there.
I have added a sample project to the repo, please check if the same bug is observed with the sample project

**Comment by ashishsakarkar2020** [comment]
Thanks Ankush. Works perfect. Was my bad .
