### ISSUE TITLE
App is crashing in OS 4.3 

### ISSUE THREAD

**Issue by sundeepkmallick** [ankushsachdeva/emojicon#7]
Hello Ankush,

Thanks for the code. I got crash for the OS 4.3. I'm not sure why it's happening!! Is there anything I'm missing. Please find the crash log below:

02-05 23:46:42.187: E/AndroidRuntime(20681): FATAL EXCEPTION: main
02-05 23:46:42.187: E/AndroidRuntime(20681): java.lang.NullPointerException
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.style.DynamicDrawableSpan.getSize(DynamicDrawableSpan.java:81)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.MeasuredText.addStyleRun(MeasuredText.java:207)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.StaticLayout.generate(StaticLayout.java:288)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at miui.dexspy.DexspyInstaller.invokeOriginalMethodNative(Native Method)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at miui.dexspy.DexspyInstaller.invokeOriginalMethod(DexspyInstaller.java:491)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at miui.dexspy.DexspyInstaller.handleHookedMethod(DexspyInstaller.java:405)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.StaticLayout.generate(Native Method)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.StaticLayout.<init>(StaticLayout.java:147)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.StaticLayout.<init>(StaticLayout.java:87)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.text.StaticLayout.<init>(StaticLayout.java:66)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.TextView.makeSingleLayout(TextView.java:6136)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.TextView.makeNewLayout(TextView.java:5976)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.TextView.onMeasure(TextView.java:6333)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.measure(View.java:15891)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5035)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.measure(View.java:15891)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.setupChild(GridView.java:1417)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.makeAndAddView(GridView.java:1344)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.makeRow(GridView.java:341)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.fillDown(GridView.java:283)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.fillFromTop(GridView.java:417)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.GridView.layoutChildren(GridView.java:1229)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.AbsListView.onLayout(AbsListView.java:2042)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.layout(View.java:14329)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewGroup.layout(ViewGroup.java:4585)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.layout(View.java:14329)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewGroup.layout(ViewGroup.java:4585)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.layout(View.java:14329)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewGroup.layout(ViewGroup.java:4585)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.View.layout(View.java:14329)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewGroup.layout(ViewGroup.java:4585)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2028)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1782)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1056)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5542)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.Choreographer.doFrame(Choreographer.java:532)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.os.Handler.handleCallback(Handler.java:730)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.os.Handler.dispatchMessage(Handler.java:92)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.os.Looper.loop(Looper.java:137)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at android.app.ActivityThread.main(ActivityThread.java:5162)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at java.lang.reflect.Method.invokeNative(Native Method)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at java.lang.reflect.Method.invoke(Method.java:525)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:756)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:572)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at miui.dexspy.DexspyInstaller.main(DexspyInstaller.java:171)
02-05 23:46:42.187: E/AndroidRuntime(20681):    at dalvik.system.NativeStart.main(Native Method)
02-05 23:46:42.217: I/Process(20681): Sending signal. PID: 20681 SIG: 9

**Comment by ankushsachdeva** [comment]
could you please confirm if you are receiving the same error while running the sample project

**Comment by sundeepkmallick** [comment]
First of all thanks for your quick response. Yes, it crashed with sample project as well.

**Comment by sundeepkmallick** [comment]
Ankush any update on above?

**Comment by ankushsachdeva** [comment]
Tried to reproduce this on Galaxy Grand 1 and 2 (The only 4.3s I could get my hands at). The sample project seems to work fine there. Also, from the logs, I am not able to decipher anything conclusive.
Which device are you using?
Also, if anyone else using this library could verify this bug, I'll push it up in my priority list.

**Comment by sundeepkmallick** [comment]
I purchased a new RedeMI 1s and testing with that. Let me give a try again and look at the root cause.

**Comment by sundeepkmallick** [comment]
Hey Ankush. Surprised!!.. it's working fine with my mobile now. Please close the issue.
