### ISSUE TITLE
Emojis rendered as ???? on server

### ISSUE THREAD

**Issue by sundeepkmallick** [ankushsachdeva/emojicon#8]
Hello Ankush,

Could you please look at the issue mentioned at basecamp. I am also getting the same issue.

http://stackoverflow.com/questions/28202788/android-get-emoji-from-emojiconedittext

**Comment by ankushsachdeva** [comment]
I dont think the problem is related to the library. Still, I have answered it, please have a look.

**Comment by sundeepkmallick** [comment]
Ankush I also tried with utf8mb4_unicode_ci at the time of implementation and tried to take advice from some of my friends who are working in PHP. No one can able to answer. It's still coming with special character. If you want I can give you the link of WS to add & view emoticons. Can I have your Skype/Email id?

**Comment by ankushsachdeva** [comment]
Please try this
https://mathiasbynens.be/notes/mysql-utf8mb4
Let me know if this works.

**Comment by ankushsachdeva** [comment]
Try this
https://mathiasbynens.be/notes/mysql-utf8mb4
Let me know if this doesnt work

**Comment by Amritpal33** [comment]
Hi Ankush,
    Thankyou for the Lovely API. but i still have the same issue. When the text of EmojiconEdittext is inserted into mysql database (with encoding uff-8/utf8mb4(tried both)) the emoticon got changed to ?????.

Can you tell me how can i send the unicode of smiley instead of the encoded emoticon OR
what is the exact encoding format of this emoticons is.

Thanks and regards
